from uiwis.elements.nav import Nav as nav
from uiwis.elements.button import Button as button
from uiwis.elements.footer import Footer as footer
from uiwis.elements.label import Label as label
from uiwis.elements.toast import Toast as toast
from uiwis.elements.markdown import Markdown as markdown
from uiwis.elements.input import Input as input
from uiwis.elements.textarea import TextArea as textarea
from uiwis.elements.table import Table as table
from uiwis.elements.toast_ui_grid import ToastUIGrid as toastuigrid
from uiwis.elements.drawer import Drawer as drawer
from uiwis.elements.link import Link as link
from uiwis.elements.upload import Upload as upload
from uiwis.elements.checkbox import Checkbox as checkbox
from uiwis.elements.dropdown import Dropdown as dropdown
from uiwis.elements.toggle import Toggle as toggle
from uiwis.elements.code import Code as code
from uiwis.elements.avatar import Avatar as avatar
from uiwis.elements.tabs import Tabs as tabs
from uiwis.elements.tabs import Tab as tab
from uiwis.elements.tabs import TabPanel as tab_panel
from uiwis.elements.tabs import TabPanels as tab_panels
from uiwis.elements.divider import Divider as divider
from uiwis.elements.form import Form as form
from uiwis.element import Element as element