import pandas as pd

df = pd.DataFrame(
    [
        {
            "col1": "val1",
            "col2": "val2",
            "col3": "val1",
            "col4": "val1asdsadasds",
            "col5": "val1",
            "col6": "val1",
            "col7": "val1",
            "col8": "val1",
            "col9": "val1",
            "col10": "val1",
            "col21": "val2",
            "col31": "val1",
            "col41": "val1asdsadasds",
            "col51": "val1",
            "col61": "val1",
            "col71": "val1",
            "col81": "val1",
            "col91": "val1",
        },
        {
            "col1": "val1",
            "col2": "val2",
            "col3": "val1",
            "col4": "val1",
            "col5": "val1",
            "col6": "val1",
            "col7": "val1",
            "col8": "val1",
            "col9": "val1",
            "col10": "val1",
            "col21": "val2",
            "col31": "val1",
            "col41": "val1asdsadasds",
            "col51": "val1",
            "col61": "val1",
            "col71": "val1",
            "col81": "val1",
            "col91": "val1",
        },
        {
            "col1": "val1",
            "col2": "val2",
            "col3": "val1",
            "col4": "val1",
            "col5": "val1",
            "col6": "val1",
            "col7": "val1",
            "col8": "val1",
            "col9": "val1",
            "col10": "val1",
            "col21": "val2",
            "col31": "val1",
            "col41": "val1asdsadasds",
            "col51": "val1",
            "col61": "val1",
            "col71": "val1",
            "col81": "val1",
            "col91": "val1",
        },
    ]
)
