name: Publish

on:
  workflow_dispatch:
    
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync
    - name: Run test
      run: |
        PYTHONPATH=. uv run pytest .
    - name: Build and publish
      run: |
        git fetch --unshallow --tags
        uv version $(git describe --tags --abbrev=0)
        uv build
        uv publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}