name: Publish

on:
  workflow_dispatch:
    
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.8.5
        poetry install
    - name: Run test
      run: |
        PYTHONPATH=. poetry run pytest .
    - name: Build and publish
      run: |
        git fetch --unshallow --tags
        poetry version $(git describe --tags --abbrev=0)
        poetry build
        poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}